### ISSUE TITLE
package.json engine requirement prevents installation under Node 6 when using yarn

### ISSUE THREAD

**Issue by sargant** [jasonmcaffee/nn#3]
The `engines` field in package.json is treated as advisory under `npm`, and isn't enforced. However, `yarn` enforces this field, and [prevents installation of this package unless run with the flags](https://github.com/yarnpkg/yarn/issues/634) `--ignore-engines`. I'm hitting this problem with a Node 6.9.1 environment.

As nevernull can actually run under Node 6 with a polyfills, can the semver be pushed down to include 6.0+?

**Comment by jasonmcaffee** [comment]
Yes, good catch!  version 1.2.3 now allows for node version 6.0 and greater. Thanks
